# Numpy

## Basics
* ndim
* shape
* size
* dtype
* itemsize

In [35]:
import numpy as np

In [44]:
a = np.arange(15)
print(a)

a = a.reshape(3,5)
print(a)

type(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


numpy.ndarray

In [45]:
print(a.shape)
print(a.ndim)
print(a.dtype)
print(a.itemsize)
print(a.size)

(3, 5)
2
int32
4
15


## Array Creation

In [46]:
a = np.array([2,3,4,]) # int type
print(a)
print(a.dtype)

b = np.array([1.2, 3.5, 5.1]) # float type
print(b.dtype)

c = np.array([1.2, 3, 4.5, 5]) # multi type
print(c.dtype)

a

[2 3 4]
int32
float64
float64


array([2, 3, 4])

In [47]:
d = np.array([(1.5, 2, 3), (4, 5, 6)])
print(d)
print(d.dtype)
d

[[1.5 2.  3. ]
 [4.  5.  6. ]]
float64


array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

## zeros, ones, empty

In [48]:
zero_np = np.zeros((3,4))
print(zero_np.dtype)
zero_np

float64


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [76]:
one_np = np.ones((2,3))
print(one_np.dtype)
print(one_np)

one_np2 = np.ones((2,1), dtype=int)
print(one_np2.dtype)
print(one_np2)

float64
[[1. 1. 1.]
 [1. 1. 1.]]
int32
[[1]
 [1]]


In [53]:
em_np2 = np.empty((2,3,4), dtype=np.int16)
em_np2

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]], dtype=int16)

## arang

In [54]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [55]:
np.arange(0, 2, 0.3)

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

## linspace

In [56]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [57]:
from numpy import pi

x = np.linspace(0, 2*pi, 100)
x

array([0.        , 0.06346652, 0.12693304, 0.19039955, 0.25386607,
       0.31733259, 0.38079911, 0.44426563, 0.50773215, 0.57119866,
       0.63466518, 0.6981317 , 0.76159822, 0.82506474, 0.88853126,
       0.95199777, 1.01546429, 1.07893081, 1.14239733, 1.20586385,
       1.26933037, 1.33279688, 1.3962634 , 1.45972992, 1.52319644,
       1.58666296, 1.65012947, 1.71359599, 1.77706251, 1.84052903,
       1.90399555, 1.96746207, 2.03092858, 2.0943951 , 2.15786162,
       2.22132814, 2.28479466, 2.34826118, 2.41172769, 2.47519421,
       2.53866073, 2.60212725, 2.66559377, 2.72906028, 2.7925268 ,
       2.85599332, 2.91945984, 2.98292636, 3.04639288, 3.10985939,
       3.17332591, 3.23679243, 3.30025895, 3.36372547, 3.42719199,
       3.4906585 , 3.55412502, 3.61759154, 3.68105806, 3.74452458,
       3.8079911 , 3.87145761, 3.93492413, 3.99839065, 4.06185717,
       4.12532369, 4.1887902 , 4.25225672, 4.31572324, 4.37918976,
       4.44265628, 4.5061228 , 4.56958931, 4.63305583, 4.69652

## Updasting

In [58]:
up = np.array([1, 2, 3.0])
print(up.dtype)

float64


## More than one dimension

In [59]:
m2 = np.array([[1,2], [3,4]])
print(m2[0][1])
m2

2


array([[1, 2],
       [3, 4]])

In [60]:
m2 = np.array([1,2,3], ndmin=2)
print(m2[0][1])
m2

2


array([[1, 2, 3]])

## reshape

In [64]:
x = np.arange(6)
x = x.reshape((2,3))
x

array([[0, 1, 2],
       [3, 4, 5]])

## zeros_like

In [71]:
x = np.arange(6)
x = np.reshape(x, (2,3))
x_dim_copy = np.zeros_like(x)

print(f"x = {id(x)}")
print(f"x_dim_copy = {id(x_dim_copy)}")

x = 2227941829008
x_dim_copy = 2227941829968


In [73]:
y = np.arange(3, dtype=float)
print(y)

y_dim_copy = np.zeros_like(y)
print(y_dim_copy)

[0. 1. 2.]
[0. 0. 0.]


## ones_like

In [80]:
x1 = np.arange(6)
x1 = np.reshape(x1, (2,3))
print(x1)

x1_copy = np.ones_like(x1)
print(x1_copy)

[[0 1 2]
 [3 4 5]]
[[1 1 1]
 [1 1 1]]


## random.rand

In [87]:
r = np.random.rand(3,2)
r

array([[0.38560754, 0.48964259],
       [0.10463573, 0.88499462],
       [0.93186619, 0.59657869]])

## Element wise Operations

In [81]:
a = np.array([20,30,40,50])
b = np.arange(4)
print(a)
print(b)

[20 30 40 50]
[0 1 2 3]


In [83]:
c = a-b
print(c)

[20 29 38 47]


In [84]:
d = b**2
print(d)

[0 1 4 9]


In [85]:
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [86]:
a < 35

array([ True,  True, False, False])

In [92]:
a *= 3
a

array([180, 270, 360, 450])

In [93]:
b += a
b

array([180, 271, 362, 453])

## Matrix Operation

In [90]:
ma = np.array([[1, 1],
               [0, 2]])
mb = np.array([[2, 0],
               [3, 4]])

print(ma * mb) # element-wise multiply
print(ma @ mb) # dot operation
print(ma.dot(mb))

[[2 0]
 [0 8]]
[[5 4]
 [6 8]]
[[5 4]
 [6 8]]


## sum, min, max, cumsum

In [97]:
aa = np.random.random((2,3))

print("sum = %f" % aa.sum())
print("min = %f" % aa.min())
print("max = %f" % aa.max())

sum = 4.264293
min = 0.213012
max = 0.963683


In [102]:
bb = np.arange(20)
bb = np.reshape(bb, (4,5))

print(bb)
print(bb.sum(axis=0))
print(bb.min(axis=1))
print(bb.cumsum(axis=0))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[30 34 38 42 46]
[ 0  5 10 15]
[[ 0  1  2  3  4]
 [ 5  7  9 11 13]
 [15 18 21 24 27]
 [30 34 38 42 46]]


## functions

In [103]:
cc = np.arange(3)
dd = np.arange(3)

print(cc)
print(np.exp(cc))
print(np.sqrt(cc))
print(np.add(cc, dd))

[0 1 2]
[1.         2.71828183 7.3890561 ]
[0.         1.         1.41421356]
[0 2 4]


## argmax

In [108]:
ee = np.arange(6).reshape(2,3) + 10

print(ee)
print(np.argmax(ee))
print(np.argmax(ee, axis=0))
print(np.argmax(ee, axis=1))

[[10 11 12]
 [13 14 15]]
5
[1 1 1]
[2 2]


## ceil, floor

In [110]:
a0 = np.array([-1.7, -1.5, -0.2, 0., 0.3, 1.5, 1.7, 2.0])

print(np.ceil(a0))
print(np.floor(a0))

[-1. -1. -0.  0.  1.  2.  2.  2.]
[-2. -2. -1.  0.  0.  1.  1.  2.]


## clip

In [113]:
a1 = np.arange(10)

print(np.clip(a1, 1, 8))
print(np.clip(a1, [3,2,1,7,5,3,1,8,9,3], 8))

[1 1 2 3 4 5 6 7 8 8]
[3 2 2 7 5 5 6 8 9 8]


## mean, median

In [116]:
b0 = np.array([[1,2], [3,4]])

print(np.mean(b0))
print(np.mean(b0, axis=0))
print(np.mean(b0, axis=1))

2.5
[2. 3.]
[1.5 3.5]


In [134]:
b1 = np.array([[10,7,4], [8,3,9]])

print(b1)
print(np.median(b1))
print(np.median(b1, axis=0))
print(np.median(b1, axis=1))

[[10  7  4]
 [ 8  3  9]]
7.5
[9.  5.  6.5]
[7. 8.]


## where

In [119]:
c0 = np.arange(10)

np.where(c0 < 5, c0, c0*10)

array([ 0,  1,  2,  3,  4, 50, 60, 70, 80, 90])

## concatenate

In [124]:
a = np.array([[1,2],
              [3,4]])
b = np.array([[5,6]]) # dimension should be same

print(np.concatenate((a, b), axis=0))
print(np.concatenate((a, b.T), axis=1))
print(np.concatenate((a, b), axis=None))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6]


## squeeze

In [133]:
c = np.array([[[0],[1],[2]]])

print(c.shape)

c0 = np.squeeze(c)
c1 = np.squeeze(c, axis=0)
c2 = np.squeeze(c, axis=2)

print(c0.shape)
print(c1.shape)
print(c2.shape)

c3 = np.squeeze(c, axis=1)

(1, 3, 1)
(3,)
(3, 1)
(1, 3)


ValueError: cannot select an axis to squeeze out which has size not equal to one

### my playground

In [138]:
print(np.array([1,2,3,4]).shape)
print(np.array([[1,2,3,4]]).shape)

(4,)
(1, 4)


In [139]:
a = np.array([[1,2],
              [3,4]])
b = np.array([5,6]) # dimension should be same

print(np.concatenate((a, b), axis=0))

ValueError: all the input arrays must have same number of dimensions